version: "3.7"

services:
    frontend:
        image: resorptionbidonvilles/resorption-bidonvilles:0.0.1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1234:80