version: "3.7"

services:
    frontend:
        image: rb-frontend:0.0.1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1234:80
        environment:
            - "API_URL=http://localhost:810"